const fs = require('fs');
const path = require('path');

const TRANSLATIONS_DIR = path.join(__dirname, 'mobile_app/assets/translations');
const LANGUAGES = ['tr', 'en', 'de', 'fr', 'it', 'es'];

const newCartKeys = {
    tr: {
        login_required: "Lütfen önce giriş yapın",
        cart_empty: "Sepetiniz boş",
        user_info_error: "Kullanıcı bilgisi alınamadı. Lütfen tekrar giriş yapın.",
        order_error: "Sipariş hatası",
        my_cart: "Sepetim",
        my_orders: "Siparişlerim",
        no_orders: "Henüz siparişiniz yok",
        no_active_orders: "Aktif siparişiniz yok",
        past_orders: "Geçmiş Siparişler",
        login_to_see_orders: "Siparişlerinizi görmek için giriş yapın",
        login: "Giriş Yap",
        select_business: "Sipariş vermek için bir işletme seçin!",
        view_order: "Siparişi Görüntüle",
        items: "ürün",
        rate: "Puan Ver",
        reorder: "Tekrar Sipariş Ver",
        order_date: "Sipariş",
        delivery_address: "Teslimat Adresi:",
        pickup: "Gel Al:",
        show_on_map: "Haritada Göster",
        total_paid: "Ödenen Toplam",
        view_receipt: "Fişi Görüntüle",
        have_a_problem: "Bir sorun mu var?",
        helper_can_assist: "Yardımcımız size yardımcı olabilir",
        start_chat: "Sohbeti Başlat",
        map_error: "Harita açılırken hata oluştu",
        date: "TARİH:",
        time: "SAAT:",
        type_delivery: "TESLİMAT",
        type_pickup: "GEL AL",
        type_label: "TİP:",
        order_no_label: "SİPARİŞ NO:"
    },
    en: {
        login_required: "Please log in first",
        cart_empty: "Your cart is empty",
        user_info_error: "Failed to get user info. Please log in again.",
        order_error: "Order error",
        my_cart: "My Cart",
        my_orders: "My Orders",
        no_orders: "You have no orders yet",
        no_active_orders: "You have no active orders",
        past_orders: "Past Orders",
        login_to_see_orders: "Log in to see your orders",
        login: "Log In",
        select_business: "Select a business to order!",
        view_order: "View Order",
        items: "items",
        rate: "Rate",
        reorder: "Reorder",
        order_date: "Order",
        delivery_address: "Delivery Address:",
        pickup: "Pickup:",
        show_on_map: "Show on Map",
        total_paid: "Total Paid",
        view_receipt: "View Receipt",
        have_a_problem: "Have a problem?",
        helper_can_assist: "Our helper can assist you",
        start_chat: "Start Chat",
        map_error: "Error opening map",
        date: "DATE:",
        time: "TIME:",
        type_delivery: "DELIVERY",
        type_pickup: "PICKUP",
        type_label: "TYPE:",
        order_no_label: "ORDER NO:"
    },
    de: {
        login_required: "Bitte loggen Sie sich zuerst ein",
        cart_empty: "Ihr Warenkorb ist leer",
        user_info_error: "Fehler beim Abrufen der Benutzerdaten. Bitte erneut anmelden.",
        order_error: "Bestellfehler",
        my_cart: "Mein Warenkorb",
        my_orders: "Meine Bestellungen",
        no_orders: "Sie haben noch keine Bestellungen",
        no_active_orders: "Sie haben keine aktiven Bestellungen",
        past_orders: "Vergangene Bestellungen",
        login_to_see_orders: "Melden Sie sich an, um Ihre Bestellungen zu sehen",
        login: "Anmelden",
        select_business: "Wählen Sie ein Geschäft, um zu bestellen!",
        view_order: "Bestellung ansehen",
        items: "Artikel",
        rate: "Bewerten",
        reorder: "Erneut bestellen",
        order_date: "Bestellung",
        delivery_address: "Lieferadresse:",
        pickup: "Abholung:",
        show_on_map: "Auf der Karte zeigen",
        total_paid: "Insgesamt bezahlt",
        view_receipt: "Quittung anzeigen",
        have_a_problem: "Haben Sie ein Problem?",
        helper_can_assist: "Unser Helfer kann Sie unterstützen",
        start_chat: "Chat starten",
        map_error: "Fehler beim Öffnen der Karte",
        date: "DATUM:",
        time: "ZEIT:",
        type_delivery: "LIEFERUNG",
        type_pickup: "ABHOLUNG",
        type_label: "TYP:",
        order_no_label: "BESTELL-NR:"
    },
    fr: {
        login_required: "Veuillez vous connecter d'abord",
        cart_empty: "Votre panier est vide",
        user_info_error: "Échec de l'obtention des infos utilisateur. Veuillez vous reconnecter.",
        order_error: "Erreur de commande",
        my_cart: "Mon Panier",
        my_orders: "Mes Commandes",
        no_orders: "Vous n'avez pas encore de commandes",
        no_active_orders: "Vous n'avez pas de commandes actives",
        past_orders: "Commandes passées",
        login_to_see_orders: "Connectez-vous pour voir vos commandes",
        login: "Connexion",
        select_business: "Sélectionnez un commerce pour commander !",
        view_order: "Voir la commande",
        items: "articles",
        rate: "Évaluer",
        reorder: "Commander à nouveau",
        order_date: "Commande",
        delivery_address: "Adresse de livraison :",
        pickup: "À emporter :",
        show_on_map: "Afficher sur la carte",
        total_paid: "Total payé",
        view_receipt: "Voir le reçu",
        have_a_problem: "Un problème ?",
        helper_can_assist: "Notre assistant peut vous aider",
        start_chat: "Démarrer le chat",
        map_error: "Erreur à l'ouverture de la carte",
        date: "DATE :",
        time: "HEURE :",
        type_delivery: "LIVRAISON",
        type_pickup: "À EMPORTER",
        type_label: "TYPE :",
        order_no_label: "N° DE COMMANDE :"
    },
    it: {
        login_required: "Per favore accedi prima",
        cart_empty: "Il tuo carrello è vuoto",
        user_info_error: "Impossibile ottenere le info utente. Effettua nuovamente l'accesso.",
        order_error: "Errore nell'ordine",
        my_cart: "Il mio Carrello",
        my_orders: "I miei Ordini",
        no_orders: "Non hai ancora ordini",
        no_active_orders: "Non hai ordini attivi",
        past_orders: "Ordini passati",
        login_to_see_orders: "Accedi per vedere i tuoi ordini",
        login: "Accedi",
        select_business: "Seleziona un'attività per ordinare!",
        view_order: "Vedi Ordine",
        items: "articoli",
        rate: "Valuta",
        reorder: "Riordina",
        order_date: "Ordine",
        delivery_address: "Indirizzo di consegna:",
        pickup: "Ritiro:",
        show_on_map: "Mostra sulla mappa",
        total_paid: "Totale pagato",
        view_receipt: "Vedi Ricevuta",
        have_a_problem: "Hai un problema?",
        helper_can_assist: "Il nostro assistente può aiutarti",
        start_chat: "Inizia Chat",
        map_error: "Errore nell'apertura della mappa",
        date: "DATA:",
        time: "ORA:",
        type_delivery: "CONSEGNA",
        type_pickup: "RITIRO",
        type_label: "TIPO:",
        order_no_label: "N. ORDINE:"
    },
    es: {
        login_required: "Inicia sesión primero",
        cart_empty: "Tu carrito está vacío",
        user_info_error: "Error al obtener la info del usuario. Por favor, inicia sesión de nuevo.",
        order_error: "Error en el pedido",
        my_cart: "Mi Carrito",
        my_orders: "Mis Pedidos",
        no_orders: "Aún no tienes pedidos",
        no_active_orders: "No tienes pedidos activos",
        past_orders: "Pedidos pasados",
        login_to_see_orders: "Inicia sesión para ver tus pedidos",
        login: "Iniciar Sesión",
        select_business: "Selecciona un negocio para pedir",
        view_order: "Ver Pedido",
        items: "artículos",
        rate: "Valorar",
        reorder: "Volver a pedir",
        order_date: "Pedido",
        delivery_address: "Dirección de entrega:",
        pickup: "Para recoger:",
        show_on_map: "Mostrar en el mapa",
        total_paid: "Total pagado",
        view_receipt: "Ver Recibo",
        have_a_problem: "¿Tienes algún problema?",
        helper_can_assist: "Nuestro asistente puede ayudarte",
        start_chat: "Iniciar Chat",
        map_error: "Error al abrir el mapa",
        date: "FECHA:",
        time: "HORA:",
        type_delivery: "ENTREGA",
        type_pickup: "RECOGER",
        type_label: "TIPO:",
        order_no_label: "Nº PEDIDO:"
    }
};

async function updateTrans() {
    for (const lang of LANGUAGES) {
        const filePath = path.join(TRANSLATIONS_DIR, `${lang}.json`);
        let content = {};
        if (fs.existsSync(filePath)) {
            content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        }

        if (!content.cart) content.cart = {};

        content.cart = {
            ...content.cart,
            ...newCartKeys[lang]
        };

        fs.writeFileSync(filePath, JSON.stringify(content, null, 4));
        console.log(`Updated ${lang}.json`);
    }
}

updateTrans();
