export interface MasterProduct {
    id: string; // SKU Matching Mobile App
    name: Record<string, string> | string;
    category: string;
    defaultUnit: 'kg' | 'ad' | string;
    description: Record<string, string> | string;
    defaultPrice?: number;  // Varsayılan fiyat (EUR)
    allowedBusinessTypes?: string[];  // Hangi işletme türleri satabilir
    imageUrl?: string; // Ürün görseli URL
}

export const MASTER_PRODUCTS: MasterProduct[] = [

    // ═══════════════════════════════════════════════════════════════
    // 🐔 GEFLÜGEL PRODUKTE / TAVUK ÜRÜNLERİ — 6 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-GP-001',
        name: { tr: 'Bütün Tavuk', de: 'Hähnchen Ganz' },
        category: 'tavuk',
        defaultUnit: 'kg',
        description: { tr: 'Bütün tavuk, temizlenmiş.', de: 'Ganzes Hähnchen, küchenfertig.' },
        defaultPrice: 6.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/452_tum_tavuk-1.jpg',
    },
    {
        id: 'TUNA-GP-002',
        name: { tr: 'Tavuk But', de: 'Hähnchenschenkel' },
        category: 'tavuk',
        defaultUnit: 'kg',
        description: { tr: 'Tavuk but, kemikli.', de: 'Hähnchenschenkel.' },
        defaultPrice: 6.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/459_tavuk_incik-1.jpg',
    },
    {
        id: 'TUNA-GP-003',
        name: { tr: 'Tavuk Göğüs', de: 'Hähnchenkeule' },
        category: 'tavuk',
        defaultUnit: 'kg',
        description: { tr: 'Tavuk göğüs.', de: 'Hähnchenkeule.' },
        defaultPrice: 11.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/453_tavuk_but-1.jpg',
    },
    {
        id: 'TUNA-GP-004',
        name: { tr: 'Tavuk Kanat', de: 'Hähnchenflügel' },
        category: 'tavuk',
        defaultUnit: 'kg',
        description: { tr: 'Tavuk kanat.', de: 'Hähnchenflügel.' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/458_tavuk_kanat-1.jpg',
    },
    {
        id: 'TUNA-GP-005',
        name: { tr: 'Tavuk Fileto 600 gr', de: 'Hähnchenfilet 600 gr' },
        category: 'tavuk',
        defaultUnit: 'ad',
        description: { tr: 'Tavuk fileto, 600 gr paket.', de: 'Hähnchenfilet, 600 gr Packung.' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/456_tavuk_gogus-1.jpg',
    },
    {
        id: 'TUNA-GP-006',
        name: { tr: 'Tavuk Pirzola', de: 'Hähnchenkoteletten' },
        category: 'tavuk',
        defaultUnit: 'kg',
        description: { tr: 'Tavuk pirzola.', de: 'Hähnchenkoteletten.' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/460_tavuk_pirzola-1.jpg',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🥩 FLEISCH PRODUKTE / ET ÜRÜNLERİ — 22 Ürün
    // ═══════════════════════════════════════════════════════════════

    // -- Kuzu (Lamm) --
    {
        id: 'TUNA-FP-001',
        name: { tr: 'Bütün Kuzu', de: 'Lamm Ganz' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Bütün kuzu, parçalanmış.', de: 'Ganzes Lamm, zerlegt.' },
        defaultPrice: 14.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/tum_kuzu-1.png',
    },
    {
        id: 'TUNA-FP-002',
        name: { tr: 'Kuzu Pirzola', de: 'Lamm-Koteletten' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu pirzola.', de: 'Lamm-Koteletten.' },
        defaultPrice: 21.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/414_Kuzu_pirzola-1.jpg',
    },
    {
        id: 'TUNA-FP-003',
        name: { tr: 'Kuzu But (Kemiksiz)', de: 'Lammkeule ohne Knochen' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu but, kemiksiz.', de: 'Lammkeule ohne Knochen.' },
        defaultPrice: 16.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/411_kuzu_but_kemiksiz-1.jpg',
    },
    {
        id: 'TUNA-FP-004',
        name: { tr: 'Kuzu İncik', de: 'Lamm Beinfleisch' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu incik.', de: 'Lamm Beinfleisch.' },
        defaultPrice: 15.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/418_kuzu_incik-1.jpg',
    },
    {
        id: 'TUNA-FP-005',
        name: { tr: 'Kuzu Kaburga', de: 'Lammrippen' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu kaburga.', de: 'Lammrippen.' },
        defaultPrice: 13.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/415_kuzu_kaburga-1.jpg',
    },
    {
        id: 'TUNA-FP-006',
        name: { tr: 'Kuzu Ciğer', de: 'Lammleber' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu ciğer.', de: 'Lammleber.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/421_kuzu_ciger-1.jpg',
    },
    {
        id: 'TUNA-FP-007',
        name: { tr: 'Kuzu Boyun', de: 'Lammhals' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu boyun eti.', de: 'Lammhals.' },
        defaultPrice: 13.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/417_kuzu_boyun-1.jpg',
    },
    {
        id: 'TUNA-FP-008',
        name: { tr: 'Kuzu But (Kemikli)', de: 'Lamm-Keule' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu but, kemikli.', de: 'Lamm-Keule am Knochen.' },
        defaultPrice: 14.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/410_kuzu_kemikli-1.jpg',
    },
    {
        id: 'TUNA-FP-009',
        name: { tr: 'Kuzu Kol', de: 'Lammschulter' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Kuzu kol eti.', de: 'Lammschulter.' },
        defaultPrice: 15.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/416_kuzu_on_kol-1.jpg',
    },
    {
        id: 'TUNA-FP-010',
        name: { tr: 'Kuzu Kelle', de: 'Lamm Schädel' },
        category: 'et',
        defaultUnit: 'ad',
        description: { tr: 'Kuzu kelle.', de: 'Lamm Schädel.' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/tunafood-temsili-urun-resmi-1.png',
    },

    // -- Dana / Jungbulle (JB) --
    {
        id: 'TUNA-FP-011',
        name: { tr: 'Dana Biftek', de: 'Roastbeef' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana biftek (roastbeef).', de: 'Roastbeef.' },
        defaultPrice: 22.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/195_roastbeef-1.jpg',
    },
    {
        id: 'TUNA-FP-012',
        name: { tr: 'Bütün Dana', de: 'Ganzes Bullenfleisch' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Bütün dana eti.', de: 'Ganzes Bullenfleisch.' },
        defaultPrice: 12.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/tosun_karkas-1.png',
    },
    {
        id: 'TUNA-FP-013',
        name: { tr: 'Dana Kontrfile', de: 'Jungbulle Contrfilet' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana kontrfile.', de: 'Jungbulle Contrfilet.' },
        defaultPrice: 29.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/196_bonfile-1.jpg',
    },
    {
        id: 'TUNA-FP-014',
        name: { tr: 'Dana Kaburga Kemikli', de: 'Jungbulle Lappen mit Knochen' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana kaburga, kemikli.', de: 'Jungbulle Lappen mit Knochen.' },
        defaultPrice: 13.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/183_tosun_kaburga_kemikli-1.jpg',
    },
    {
        id: 'TUNA-FP-015',
        name: { tr: 'Dana Tantuni Eti', de: 'Jungbulle Tantuni Fleisch' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana tantuni eti, ince doğranmış.', de: 'Jungbulle Tantuni Fleisch, fein geschnitten.' },
        defaultPrice: 18.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/189_tosun_tantuni-1.jpg',
    },
    {
        id: 'TUNA-FP-016',
        name: { tr: 'Dana Kuşbaşı', de: 'Jungbulle Gulaschfleisch' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana kuşbaşı, güveç için ideal.', de: 'Jungbulle Gulaschfleisch.' },
        defaultPrice: 17.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/192_tosun_kusbasi-1.jpg',
    },
    {
        id: 'TUNA-FP-017',
        name: { tr: 'Dana Lop Et', de: 'Jungbulle Teilstück' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana lop eti.', de: 'Jungbulle Teilstück.' },
        defaultPrice: 15.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/186_tosun_parca-1.jpg',
    },
    {
        id: 'TUNA-FP-018',
        name: { tr: 'Yağsız Kıyma 2 Kg', de: 'Hackfleisch Mager 2 kg' },
        category: 'et',
        defaultUnit: 'ad',
        description: { tr: 'Yağsız kıyma, 2 kg paket.', de: 'Hackfleisch Mager, 2 kg Packung.' },
        defaultPrice: 29.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/210_yagsiz_kiyma-1.jpg',
    },
    {
        id: 'TUNA-FP-019',
        name: { tr: 'Dana Kıyma (Normal)', de: 'Rinderhackfleisch Normal' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana kıyma, normal yağ oranı.', de: 'Rinderhackfleisch, normaler Fettanteil.' },
        defaultPrice: 13.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/204_azyagli_kiyma-1.jpg',
    },
    {
        id: 'TUNA-FP-020',
        name: { tr: 'Dana Kıyma (Yağlı)', de: 'Rinderhackfleisch Fettig' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana kıyma, yağlı.', de: 'Rinderhackfleisch, fettig.' },
        defaultPrice: 11.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/207_yagli_kiyma-1.jpg',
    },

    // -- Sakatat --
    {
        id: 'TUNA-FP-021',
        name: { tr: 'Dana Dil', de: 'Rinderzunge' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana dil.', de: 'Rinderzunge.' },
        defaultPrice: 14.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/359_sutdana_dil-1.jpg',
    },
    {
        id: 'TUNA-FP-022',
        name: { tr: 'Dana İşkembe', de: 'Rind Pansen' },
        category: 'et',
        defaultUnit: 'kg',
        description: { tr: 'Dana işkembe.', de: 'Rind Pansen.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/358_sutdana_iskembe-1.jpg',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🧊 TIEFKÜHL PRODUKTE / DONDURULMUŞ ÜRÜNLER — 14 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-TK-001',
        name: { tr: 'Ev Tipi Döner 500 gr', de: 'Doner für zu Hause 500 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Ev tipi döner.', de: 'Doner für zu Hause.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/673_ev_tipi_doner-1.jpg',
    },
    {
        id: 'TUNA-TK-002',
        name: { tr: 'Kesilmiş Kıyma Döner 500 gr', de: 'Fleisch Doner gar 500 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Kesilmiş kıyma döner.', de: 'Fleisch Doner gar.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/851_et_doner-1.png',
    },
    {
        id: 'TUNA-TK-003',
        name: { tr: 'Kesilmiş Tavuk Döner 500 gr', de: 'Hähnchen Doner gar 500 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Kesilmiş tavuk döner.', de: 'Hähnchen Doner gar.' },
        defaultPrice: 9.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/852_tavuk_doner-1.png',
    },
    {
        id: 'TUNA-TK-004',
        name: { tr: 'Tavuk Nugget 500 gr', de: 'Hähnchen Nuggets 500 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Tavuk nugget, dondurulmuş.', de: 'Hähnchen Nuggets, tiefgekühlt.' },
        defaultPrice: 6.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/684_tavuk_nugget_500g-1.png',
    },
    {
        id: 'TUNA-TK-005',
        name: { tr: 'Tavuk Fileto 600 gr', de: 'Hähnchen-Fileto 600 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Dondurulmuş tavuk fileto.', de: 'Hähnchen-Fileto, tiefgekühlt.' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/686_tavuk_fileto_600g-1.png',
    },
    {
        id: 'TUNA-TK-006',
        name: { tr: 'Çıtır Tavuk Burger 540 gr', de: 'Hähnchen Burger 540 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Çıtır tavuk burger.', de: 'Hähnchen Burger.' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/685_tavuk_burger_540g-1.png',
    },
    {
        id: 'TUNA-TK-007',
        name: { tr: 'Dana Burger 600 gr', de: 'Rinds-Burger 600 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Dana burger.', de: 'Rinds-Burger.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/656_dana_burger_600g-1.png',
    },
    {
        id: 'TUNA-TK-008',
        name: { tr: 'TUNA Köfte 600 gr', de: 'Tuna Buletten 600 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'TUNA köfte.', de: 'Tuna Buletten.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/659_tuna_kofte_600g-1.png',
    },
    {
        id: 'TUNA-TK-009',
        name: { tr: 'İnegöl Köfte 600 gr', de: 'İnegöl Buletten 600 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'İnegöl köfte.', de: 'İnegöl Buletten.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/658_inegol_kofte_600g-1.png',
    },
    {
        id: 'TUNA-TK-010',
        name: { tr: 'Adana Kebap 560 gr', de: 'Adana Kebap 560 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Adana kebap.', de: 'Adana Kebap.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/657_adana_kebap_560g-1.png',
    },
    {
        id: 'TUNA-TK-011',
        name: { tr: 'Kıymalı Döner Bağırsak 500 gr', de: 'Normales Hackfleisch im Darm 500 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Kıymalı döner, bağırsak içinde.', de: 'Normales Hackfleisch im Darm.' },
        defaultPrice: 9.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/672_ev_tipi_kiyma-1.jpg',
    },
    {
        id: 'TUNA-TK-012',
        name: { tr: 'Mantı 750 gr', de: 'Mantı 750 g' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Türk mantısı.', de: 'Türkische Teigtaschen (Mantı).' },
        defaultPrice: 7.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/688_tuna_manti_750g-1.png',
    },
    {
        id: 'TUNA-TK-013',
        name: { tr: 'Lahmacun', de: 'Lahmacun' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Lahmacun.', de: 'Türkische Pizza (Lahmacun).' },
        defaultPrice: 6.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2024/03/lahmacun.jpg',
    },
    {
        id: 'TUNA-TK-014',
        name: { tr: 'Sucuklu Pizza', de: 'Pizza Sucuk' },
        category: 'dondurulmus',
        defaultUnit: 'ad',
        description: { tr: 'Sucuklu pizza.', de: 'Pizza mit Knoblauchwurst.' },
        defaultPrice: 7.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2024/03/pizza-sucuk.jpg',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🌭 WÜRSTCHEN / SOSİS — 7 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-WU-001',
        name: { tr: 'Sığır Sosis 400 gr', de: 'Rindswürstchen 400 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Sığır sosis.', de: 'Rindswürstchen.' },
        defaultPrice: 6.25,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/sigir_sosis_konserve-1.png',
    },
    {
        id: 'TUNA-WU-002',
        name: { tr: 'Tavuk Sosis 400 gr', de: 'Hähnchenwürstchen 400 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Tavuk sosis.', de: 'Hähnchenwürstchen.' },
        defaultPrice: 5.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/656_tavuk_sosis_400g-1.png',
    },
    {
        id: 'TUNA-WU-003',
        name: { tr: 'Izgara Sosis 500 gr', de: 'Grillwürstchen 500 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Izgara sosis.', de: 'Grillwürstchen.' },
        defaultPrice: 6.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/sigir_sosis_konserve-1.png',
    },
    {
        id: 'TUNA-WU-004',
        name: { tr: 'Jumbo Sığır Sosis 500 gr', de: 'Jumbo-Rindswürstchen 500 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Jumbo sığır sosis.', de: 'Jumbo-Rindswürstchen.' },
        defaultPrice: 7.25,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/sigir_sosis_konserve-1.png',
    },
    {
        id: 'TUNA-WU-005',
        name: { tr: 'Sığır Sosis 600 gr', de: 'Rindswürstchen 600 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Sığır sosis, 600 gr paket.', de: 'Rindswürstchen, 600 g Packung.' },
        defaultPrice: 8.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/sigir_sosis_konserve-1.png',
    },
    {
        id: 'TUNA-WU-006',
        name: { tr: 'Sığır Sosis Teneke 250 gr', de: 'Rindswürstchen in der Dose 250 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Sığır sosis, teneke kutu.', de: 'Rindswürstchen in der Dose.' },
        defaultPrice: 4.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/sigir_sosis_konserve-1.png',
    },
    {
        id: 'TUNA-WU-007',
        name: { tr: 'Tavuk Sosis Teneke 250 gr', de: 'Hähnchenwürstchen in der Dose 250 g' },
        category: 'wurstchen',
        defaultUnit: 'ad',
        description: { tr: 'Tavuk sosis, teneke kutu.', de: 'Hähnchenwürstchen in der Dose.' },
        defaultPrice: 4.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/tavuk_sosis_konserve-1.png',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🥓 WURST / SALAM — 6 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-WR-001',
        name: { tr: 'Sığır Dilim Salam 150 gr', de: 'Rindswurst in Scheiben 150 g' },
        category: 'wurst',
        defaultUnit: 'ad',
        description: { tr: 'Sığır dilim salam.', de: 'Rindswurst in Scheiben.' },
        defaultPrice: 2.69,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/596_dilim_sigir_salam_200g-1.png',
    },
    {
        id: 'TUNA-WR-002',
        name: { tr: 'Biberli Sığır Dilim Salam 150 gr', de: 'Rindfleischwurst in Scheiben mit Paprika 150 g' },
        category: 'wurst',
        defaultUnit: 'ad',
        description: { tr: 'Biberli sığır dilim salam.', de: 'Rindfleischwurst in Scheiben mit Paprika.' },
        defaultPrice: 2.69,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/597_dilim_biberli_salam_200g-1.png',
    },
    {
        id: 'TUNA-WR-003',
        name: { tr: 'Tavuk Dilim Salam 150 gr', de: 'Hähnchenwurst in Scheiben 150 g' },
        category: 'wurst',
        defaultUnit: 'ad',
        description: { tr: 'Tavuk dilim salam.', de: 'Hähnchenwurst in Scheiben.' },
        defaultPrice: 2.69,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/598_dilim_tavuk_salam_200g-1.png',
    },
    {
        id: 'TUNA-WR-004',
        name: { tr: 'Macar Salam 400 gr', de: 'Salami ungarisch 400 g' },
        category: 'wurst',
        defaultUnit: 'ad',
        description: { tr: 'Macar salam.', de: 'Salami ungarisch.' },
        defaultPrice: 6.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/599_macar_salam_2-1.png',
    },
    {
        id: 'TUNA-WR-005',
        name: { tr: 'Sığır Salam 400 gr', de: 'Rindswurst 400 g' },
        category: 'wurst',
        defaultUnit: 'ad',
        description: { tr: 'Sığır salam baton.', de: 'Rindswurst Stange.' },
        defaultPrice: 5.79,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/561_sade_salam_baton_400g-1.png',
    },
    {
        id: 'TUNA-WR-006',
        name: { tr: 'Tavuk Salam 400 gr', de: 'Hähnchenwurst 400 g' },
        category: 'wurst',
        defaultUnit: 'ad',
        description: { tr: 'Tavuk salam baton.', de: 'Hähnchenwurst Stange.' },
        defaultPrice: 4.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/567_tavuk_salam_baton_400g-1.png',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🧄 SUCUK — 8 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-SK-001',
        name: { tr: 'Orta Acı Sucuk 1000 gr', de: 'Mittelscharf Sucuk 1000 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Orta acılı sucuk, 1 kg.', de: 'Mittelscharf Sucuk, 1 kg.' },
        defaultPrice: 15.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/501_parmak_sucuk_1kg_2-1.png',
    },
    {
        id: 'TUNA-SK-002',
        name: { tr: 'Kangal Sucuk 1000 gr', de: 'Kangal Sucuk 1000 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Kangal sucuk, 1 kg.', de: 'Kangal Sucuk, 1 kg.' },
        defaultPrice: 15.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/502_kangal_sucuk_1kg_2-1.png',
    },
    {
        id: 'TUNA-SK-003',
        name: { tr: 'Ekstra Acı Sucuk 1000 gr', de: 'Extra Scharf Sucuk 1000 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Ekstra acılı sucuk, 1 kg.', de: 'Extra Scharf Sucuk, 1 kg.' },
        defaultPrice: 15.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/503_sadrazam_sucuk_1kg-1.png',
    },
    {
        id: 'TUNA-SK-004',
        name: { tr: 'Dilim Sucuk 250 gr', de: 'Sucuk in Scheiben 250 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Dilim sucuk.', de: 'Sucuk in Scheiben.' },
        defaultPrice: 4.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/101_dilim_sucuk_2-1.png',
    },
    {
        id: 'TUNA-SK-005',
        name: { tr: 'Sucuk Burger 250 gr', de: 'Sucuk Burger 250 gr' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Sucuk burger.', de: 'Sucuk Burger.' },
        defaultPrice: 4.49,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/508_de_sucuk_burger_250gr.png',
    },
    {
        id: 'TUNA-SK-006',
        name: { tr: 'Mini Sucuk 30 gr', de: 'Mini Sucuk 30 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Mini sucuk.', de: 'Mini Sucuk.' },
        defaultPrice: 1.25,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/507_mini_sucuk-1.png',
    },
    {
        id: 'TUNA-SK-007',
        name: { tr: 'Orta Acı Sucuk 400 gr', de: 'Mittelscharf Sucuk 400 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Orta acılı sucuk, 400 gr.', de: 'Mittelscharf Sucuk, 400 g.' },
        defaultPrice: 6.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/504_parmak_sucuk_400g_2-1.png',
    },
    {
        id: 'TUNA-SK-008',
        name: { tr: 'Ekstra Acı Sucuk 400 gr', de: 'Extra Scharf Sucuk 400 g' },
        category: 'sucuk',
        defaultUnit: 'ad',
        description: { tr: 'Ekstra acılı sucuk, 400 gr.', de: 'Extra Scharf Sucuk, 400 g.' },
        defaultPrice: 6.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/11/506_sadrazam_sucuk_400g-1.png',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🥓 RINDERROHSCHINKEN / PASTIRMA — 1 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-RS-001',
        name: { tr: 'Pastırma 100 gr', de: 'Rinderrohschinken 100 g' },
        category: 'pastirma',
        defaultUnit: 'ad',
        description: { tr: 'Pastırma.', de: 'Rinderrohschinken nach türkischer Art.' },
        defaultPrice: 3.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2020/12/Pastirma_1x.png',
    },

    // ═══════════════════════════════════════════════════════════════
    // 🍖 BRATEN / KAVURMA — 2 Ürün
    // ═══════════════════════════════════════════════════════════════
    {
        id: 'TUNA-BR-001',
        name: { tr: 'Kavurma 3 Kg', de: 'Gebratenes Rindfleisch 3 Kg' },
        category: 'kavurma',
        defaultUnit: 'ad',
        description: { tr: 'Kavurma, 3 kg paket.', de: 'Gebratenes Rindfleisch, 3 kg.' },
        defaultPrice: 74.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2024/03/tunafood-baton-kavurma-582.png',
    },
    {
        id: 'TUNA-BR-002',
        name: { tr: 'Kavurma (Kesilmiş)', de: 'Gebratenes Rindfleisch, Geschnitten' },
        category: 'kavurma',
        defaultUnit: 'kg',
        description: { tr: 'Kavurma, doğranmış.', de: 'Gebratenes Rindfleisch, geschnitten.' },
        defaultPrice: 24.99,
        allowedBusinessTypes: ['kasap'],
        imageUrl: 'https://tunafood.com/wp-content/uploads/2024/03/tunafood-dilim-kavurma-589.png',
    },
];
