// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-AscGg-C6HuvA2xLbFJ_yGFcfRp20Fs',
    appId: '1:259070566992:web:5fe4cd150c1e30091e2755',
    messagingSenderId: '259070566992',
    projectId: 'aylar-a45af',
    authDomain: 'aylar-a45af.firebaseapp.com',
    storageBucket: 'aylar-a45af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm92A_RuTIj85tFR0LKQo80A6aTgBffgA',
    appId: '1:259070566992:android:533bbfa3a5d8c2111e2755',
    messagingSenderId: '259070566992',
    projectId: 'aylar-a45af',
    storageBucket: 'aylar-a45af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GSWm0DtaagUw5tvO4kTv085du53j_Wk',
    appId: '1:259070566992:ios:ef88784b6d6192e71e2755',
    messagingSenderId: '259070566992',
    projectId: 'aylar-a45af',
    storageBucket: 'aylar-a45af.firebasestorage.app',
    androidClientId: '259070566992-2p5md1ubl3oqmndqn7rait9mbqfgtfng.apps.googleusercontent.com',
    iosClientId: '259070566992-5oqs2q5tgkrg6rfbddot5fgj08nec03u.apps.googleusercontent.com',
    iosBundleId: 'shop.lokma.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GSWm0DtaagUw5tvO4kTv085du53j_Wk',
    appId: '1:259070566992:ios:e690e6fb79b5b2b81e2755',
    messagingSenderId: '259070566992',
    projectId: 'aylar-a45af',
    storageBucket: 'aylar-a45af.firebasestorage.app',
    androidClientId: '259070566992-2p5md1ubl3oqmndqn7rait9mbqfgtfng.apps.googleusercontent.com',
    iosClientId: '259070566992-o4fjd1to3rfvagj1j1hb5e1is85fac46.apps.googleusercontent.com',
    iosBundleId: 'com.lokma.lokmaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1-AscGg-C6HuvA2xLbFJ_yGFcfRp20Fs',
    appId: '1:259070566992:web:5fe4cd150c1e30091e2755',
    messagingSenderId: '259070566992',
    projectId: 'aylar-a45af',
    authDomain: 'aylar-a45af.firebaseapp.com',
    storageBucket: 'aylar-a45af.firebasestorage.app',
  );

}